- name: PIV Check
  hosts: jumpbox
  gather_facts: true
  roles:
    - name: osp-facts  

- name: setup HAProxy - load-balancer
  hosts: frontends	
  tasks:
     - name: PIV to confirm the HA proxy works
       uri:
          url: http://localhost
          return_content: yes
       register: haproxy
       failed_when: "'Welcome' not in haproxy.content"
